project:
  type: website
  render:
    - "*.qmd"
  resources:
    - "img/"
    - "www/"
format:
  html:
    theme:
      - united
      - www/style.scss
    toc: true
    highlight-style: monokai

execute:
  freeze: auto

website:
  title: "Causal Inference"
  site-url: "https://sta-779-s25.github.io/website"
  navbar:
    pinned: true
    background: "#533146"
    right:
      - schedule.qmd
      - syllabus.qmd
      - href: "https://rstudio.deac.wfu.edu"
        text: "{{< fa cloud >}} RStudio Pro"
    

  page-footer:
    left: "Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}})"
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

  favicon: "/images/icon.png"