on:
  push:
    branches: main
  workflow_dispatch:

name: renderbook

jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Setup dependencies
        run: | 
          sudo apt-get update
          sudo apt install libcurl4-openssl-dev
          sudo apt-get install libmagick++-dev
      
      - uses: r-lib/actions/setup-r@v2
            
      - uses: r-lib/actions/setup-renv@v2

      - name: Install packages
        shell: Rscript {0}
        run: |
         if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
         renv::restore()

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}